import json
from typing import Optional
from domain.schemas import RPMAlert, TriageDecision, EHRFindings, AnamnesisFindings, ClinicalContextBrief
from agents.base_agent import BaseAgent
from domain.confidence_calculator import ConfidenceCalculator
from domain.validators import SafetyValidator

class SynthesisAgent(BaseAgent):
    def __init__(self, version: str = "v1.0"):
        super().__init__("synthesis_agent", version)
        self.confidence_calculator = ConfidenceCalculator()
        self.safety_validator = SafetyValidator()
        
    async def synthesize(
        self,
        alert: RPMAlert,
        triage: TriageDecision,
        ehr_findings: Optional[EHRFindings],
        anamnesis_findings: Optional[AnamnesisFindings]
    ) -> ClinicalContextBrief:
        
        input_data = {
            "alert": alert.model_dump(),
            "triage": triage.model_dump(),
            "ehr_findings": ehr_findings.model_dump() if ehr_findings else None,
            "anamnesis_findings": anamnesis_findings.model_dump() if anamnesis_findings else None
        }
        
        user_prompt = f"Synthesize the following data into a CCB:\n{json.dumps(input_data, indent=2, default=str)}"
        
        try:
            ccb = await self.run_structured(user_prompt, ClinicalContextBrief)
            
            # Override confidence score with deterministic calculation
            ccb.confidence_score = self.confidence_calculator.calculate(ehr_findings, anamnesis_findings)
            
            # Validate safety
            validation = self.safety_validator.validate(ccb)
            if not validation.passed:
                raise ValueError(f"Safety violation generated by SynthesisAgent: {validation.violations}")
                
            return ccb
        except Exception as e:
            raise RuntimeError(f"Failed to execute SynthesisAgent: {str(e)}")
